const fs = require('node:fs');
const path = require('node:path');

function loadJsonOrEmpty(relativePath) {
  const fullPath = path.join(__dirname, relativePath);
  if (!fs.existsSync(fullPath)) return null;
  return JSON.parse(fs.readFileSync(fullPath, 'utf8'));
}

function docIdForAccount(code, accountsByCode) {
  const parts = [];
  let current = accountsByCode.get(code);
  while (current) {
    parts.push(current.code);
    current = current.parent_code ? accountsByCode.get(current.parent_code) : null;
  }
  parts.reverse();
  return `plan-completo/${parts.join('/')}/index`;
}

function buildTreeItems(rootCodes, accountsByCode, childrenByCode) {
  const visited = new Set();

  function walk(code) {
    if (visited.has(code)) return null;
    visited.add(code);

    const account = accountsByCode.get(code);
    if (!account) return null;

    const childCodes = (childrenByCode.get(code) || []).slice();
    childCodes.sort((a, b) => a.localeCompare(b, 'es', { numeric: true }));

    return {
      type: 'category',
      label: `${account.code} — ${account.name}`,
      link: { type: 'doc', id: docIdForAccount(account.code, accountsByCode) },
      collapsed: true,
      items: childCodes.map(walk).filter(Boolean)
    };
  }

  return rootCodes.map(walk).filter(Boolean);
}

function buildMxSidebar() {
  const accounts = loadJsonOrEmpty('data/mx/sat_accounts.json') || [];
  const profiles = loadJsonOrEmpty('data/mx/profiles/index.json') || [];
  const planGeneratedMarker = path.join(__dirname, 'docs', 'mx', 'plan-completo', '.generated.json');
  const esqueletosGeneratedMarker = path.join(__dirname, 'docs', 'mx', 'esqueletos', '.generated.json');

  const accountsByCode = new Map(accounts.map((a) => [a.code, a]));
  const childrenByCode = new Map();
  for (const a of accounts) {
    if (!a.parent_code) continue;
    const list = childrenByCode.get(a.parent_code) || [];
    list.push(a.code);
    childrenByCode.set(a.parent_code, list);
  }

  const roots = accounts
    .filter((a) => !a.parent_code)
    .map((a) => a.code)
    .sort((a, b) => a.localeCompare(b, 'es', { numeric: true }));

  const planCompletoItems = fs.existsSync(planGeneratedMarker)
    ? buildTreeItems(roots, accountsByCode, childrenByCode)
    : [];

  const esqueletosItems = fs.existsSync(esqueletosGeneratedMarker)
    ? profiles
        .slice()
        .sort((a, b) => a.title.localeCompare(b.title, 'es'))
        .map((p) => ({ type: 'doc', id: `esqueletos/${p.id}/index`, label: p.title }))
    : [];

  return [
    { type: 'doc', id: 'intro' },
    {
      type: 'category',
      label: 'Plan completo',
      link: { type: 'doc', id: 'plan-completo/index' },
      items: planCompletoItems
    },
    {
      type: 'category',
      label: 'Esqueletos',
      link: { type: 'doc', id: 'esqueletos/index' },
      items: esqueletosItems
    },
    {
      type: 'category',
      label: 'Glosario',
      link: { type: 'generated-index', title: 'Glosario (MX)', slug: '/mx/glosario' },
      items: [{ type: 'autogenerated', dirName: 'glosario' }]
    },
    {
      type: 'category',
      label: 'Notas',
      link: { type: 'generated-index', title: 'Notas (MX)', slug: '/mx/notas' },
      items: [{ type: 'autogenerated', dirName: 'notas' }]
    }
  ];
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mxSidebar: buildMxSidebar()
};

module.exports = sidebars;
